export const env = {
  MAIN_REGION: process.env.MAIN_REGION || "",
  // Cognito Admin
  PROVIDER_AUTHPOOL_ID: process.env.PROVIDER_AUTHPOOL_ID || "",
  PROVIDER_AUTHPOOL_CLIENT_ID: process.env.PROVIDER_AUTHPOOL_CLIENT_ID || "",
  // Cognito Nanapocke
  NANAPOCKE_AUTHPOOL_ID: process.env.NANAPOCKE_AUTHPOOL_ID || "",
  NANAPOCKE_AUTHPOOL_CLIENT_ID: process.env.NANAPOCKE_AUTHPOOL_CLIENT_ID || "",

  // S3
  BUCKET_UPLOAD_NAME: process.env.BUCKET_UPLOAD_NAME || "",
  BUCKET_PHOTO_NAME: process.env.BUCKET_PHOTO_NAME || "",

  // SQS
  SQS_QUEUE_URL_MAIN: process.env.SQS_QUEUE_URL_MAIN || "",
  SQS_JOB_SEND_PHOTO_FILE_BY_ORDERID: "SqsJobSendPhotoFileByOrderId",

  // Cloudfront Verify Token
  X_ORIGIN_VERIFY_TOKEN: process.env.X_ORIGIN_VERIFY_TOKEN || "",

  // SSM パラメータストアKey
  PEM_KEYPATH_PHOTO_UPLOAD_PRIVATE:
    process.env.PEM_KEYPATH_PHOTO_UPLOAD_PRIVATE || "",

  // ナナポケ認証関連
  EXT_NANAPOCKE_API_URL_ACCESS_TOKEN:
    process.env.EXT_NANAPOCKE_API_URL_ACCESS_TOKEN || "",
  EXT_NANAPOCKE_API_URL_USER_INFO:
    process.env.EXT_NANAPOCKE_API_URL_USER_INFO || "",
  EXT_NANAPOCKE_SETTING_CLIENTID:
    process.env.EXT_NANAPOCKE_SETTING_CLIENTID || "",
  EXT_NANAPOCKE_SETTING_CLIENTSECRET:
    process.env.EXT_NANAPOCKE_SETTING_CLIENTSECRET || "",
  EXT_NANAPOCKE_SETTING_GRANTTYPE:
    process.env.EXT_NANAPOCKE_SETTING_GRANTTYPE || "",
  EXT_NANAPOCKE_API_URL_ACCESS_TOKEN_REDIRECT:
    process.env.EXT_NANAPOCKE_API_URL_ACCESS_TOKEN_REDIRECT || "",
};
