export const env = {
  MAIN_REGION: process.env.MAIN_REGION || "",
  NANAPHOTO_FQDN: process.env.NANAPHOTO_FQDN || "",
  // Cognito Admin
  PROVIDER_AUTHPOOL_ID: process.env.PROVIDER_AUTHPOOL_ID || "",
  PROVIDER_AUTHPOOL_CLIENT_ID: process.env.PROVIDER_AUTHPOOL_CLIENT_ID || "",
  // Cognito Nanapocke
  NANAPOCKE_AUTHPOOL_ID: process.env.NANAPOCKE_AUTHPOOL_ID || "",
  NANAPOCKE_AUTHPOOL_CLIENT_ID: process.env.NANAPOCKE_AUTHPOOL_CLIENT_ID || "",

  // S3
  BUCKET_UPLOAD_NAME: process.env.BUCKET_UPLOAD_NAME || "",
  BUCKET_PHOTO_NAME: process.env.BUCKET_PHOTO_NAME || "",
  BUCKET_LIBRARY_NAME: process.env.BUCKET_LIBRARY_NAME || "",

  // SQS
  SQS_QUEUE_URL_MAIN: process.env.SQS_QUEUE_URL_MAIN || "",
  SQS_QUEUE_URL_PHOTO_CONVERT: process.env.SQS_QUEUE_URL_PHOTO_CONVERT || "",
  SQS_JOB_SEND_PHOTO_FILE_BY_ORDERID: "SqsJobSendPhotoFileByOrderId",
  SQS_JOB_PHOTO_UNZIP_BEFORE_SAVE: "SqsJobPhotoUnzipBeforeSave",

  // Cloudfront Verify Token
  X_ORIGIN_VERIFY_TOKEN: process.env.X_ORIGIN_VERIFY_TOKEN || "",

  // SSM パラメータストアKey
  PEM_KEYPATH_PHOTO_UPLOAD_PRIVATE:
    process.env.PEM_KEYPATH_PHOTO_UPLOAD_PRIVATE || "",

  CF_PUBLIC_KEY_THUMBNAIL_URL_KEYID:
    process.env.CF_PUBLIC_KEY_THUMBNAIL_URL_KEYID || "",
  PEM_THUMBNAIL_PREVIEW_KEYPATH:
    process.env.PEM_THUMBNAIL_PREVIEW_KEYPATH || "",

  SSM_SHIPPING_NOTIRY_SECRET_KEY:
    process.env.SSM_SHIPPING_NOTIRY_SECRET_KEY || "",

  // ナナポケ認証関連
  EXT_NANAPOCKE_API_URL_ACCESS_TOKEN:
    process.env.EXT_NANAPOCKE_API_URL_ACCESS_TOKEN || "",
  EXT_NANAPOCKE_API_URL_USER_INFO:
    process.env.EXT_NANAPOCKE_API_URL_USER_INFO || "",
  EXT_NANAPOCKE_API_URL_ACCESS_TOKEN_REDIRECT:
    process.env.EXT_NANAPOCKE_API_URL_ACCESS_TOKEN_REDIRECT || "",
};
