export const env = {
  MAIN_REGION: process.env.MAIN_REGION || "",
  // Cognito Admin
  PROVIDER_AUTHPOOL_ID: process.env.PROVIDER_AUTHPOOL_ID || "",
  PROVIDER_AUTHPOOL_CLIENT_ID: process.env.PROVIDER_AUTHPOOL_CLIENT_ID || "",
  // Cognito Nanapocke
  NANAPOCKE_AUTHPOOL_ID: process.env.NANAPOCKE_AUTHPOOL_ID || "",
  NANAPOCKE_AUTHPOOL_CLIENT_ID: process.env.NANAPOCKE_AUTHPOOL_CLIENT_ID || "",
  NANAPOCKE_AUTHPOOL_PHOTOGRAPHER_CLIENT_ID:
    process.env.NANAPOCKE_AUTHPOOL_PHOTOGRAPHER_CLIENT_ID || "",
  // Cloudfront Verify Token
  X_ORIGIN_VERIFY_TOKEN: process.env.X_ORIGIN_VERIFY_TOKEN || "",
  // ナナポケ認証関連
  EXT_NANAPOCKE_API_URL_ACCESS_TOKEN:
    process.env.EXT_NANAPOCKE_API_URL_ACCESS_TOKEN || "",
  EXT_NANAPOCKE_API_URL_USER_INFO:
    process.env.EXT_NANAPOCKE_API_URL_USER_INFO || "",
  EXT_NANAPOCKE_SETTING_CLIENTID:
    process.env.EXT_NANAPOCKE_SETTING_CLIENTID || "",
  EXT_NANAPOCKE_SETTING_CLIENTSECRET:
    process.env.EXT_NANAPOCKE_SETTING_CLIENTSECRET || "",
  EXT_NANAPOCKE_SETTING_GRANTTYPE:
    process.env.EXT_NANAPOCKE_SETTING_GRANTTYPE || "",
  EXT_NANAPOCKE_API_URL_ACCESS_TOKEN_REDIRECT:
    process.env.EXT_NANAPOCKE_API_URL_ACCESS_TOKEN_REDIRECT || "",
};
