export const appSettings = {
  reelTypeList: ['A', 'B'],
  reelPreviewTypeList: ['REEL', 'SHORT_REEL', 'POSTER'],
  reelActionTypeList: ['ITEM_LIST', 'LINK', 'HIDDEN'],
  reelButtonIconList: [
    'NONE',
    'SHOPPING_BAG',
    'SHOPPING_CART',
    'BARS_3',
    'LINK',
    'GLOBE_ALT',
    'MAP_PIN',
    'CHAT_BUBBLE_LEFT_RIGHT',
    'BUILDING_STOREFRONT',
    'BUILDING_OFFICE_2',
    'HOME',
    'WRENCH_SCREWDRIVER',
    'PHOTO',
    'FILM',
    'CLOCK',
    'MUSICAL_NOTE',
    'CAKE',
    'GIFT',
    'TROPHY',
    'FLAG',
    'SPARKLES',
    'FACE_SMILE',
  ],
  reelAspectRatioList: ['ASPECT_9_16', 'ASPECT_16_9', 'ASPECT_1_1'],
  playlistPreviewSettingList: ['FORCE_REEL_DISPLAY', 'FORCE_SHORT_REEL_DISPLAY', 'FORCE_POSTER_DISPLAY', 'FOLLOW_REEL_SETTING'],
  memberPostionList: ['MANAGER', 'REGULAR'],
};
